
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.text.NumberFormat;
import java.text.ParseException;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @authors
 * Felix Ulises Mancinas Zamora 22550029
 * Jesús Iván García Delgado 22550015
 * José de Jesús Hernández Vázquez 22550025
 * Sergio Eduardo Lastiri Torres 22550031
 *
 */



public class frmVentana extends javax.swing.JFrame implements
        MouseListener{

    private int edadActual = 0;
    private int edadRestante = 0;
    
    /**
     * Creates new form frmVentana
     */
    public frmVentana() {
        initComponents();
        
        radHombre.addMouseListener(this);
    }
    
    public void disableButtons(){
        radBebedorNo.setEnabled(false);
        radBebedorSi.setEnabled(false);
        radBoxeo.setEnabled(false);
        radCorrer.setEnabled(false);
        radCronicasNo.setEnabled(false);
        radCronicasSi.setEnabled(false);
        radFumadorNo.setEnabled(false);
        radFumadorSi.setEnabled(false);
        radHombre.setEnabled(false);
        radMaestro.setEnabled(false);
        radMujer.setEnabled(false);
        radNadar.setEnabled(false);
        radNinguna.setEnabled(false);
        radOficina.setEnabled(false);
        radSeguridad.setEnabled(false);
        btnReiniciar.setEnabled(false);
        
    }
    
    public void enableButtons(){
        radBebedorNo.setEnabled(true);
        radBebedorSi.setEnabled(true);
        radBoxeo.setEnabled(true);
        radCorrer.setEnabled(true);
        radCronicasNo.setEnabled(true);
        radCronicasSi.setEnabled(true);
        radFumadorNo.setEnabled(true);
        radFumadorSi.setEnabled(true);
        radHombre.setEnabled(true);
        radMaestro.setEnabled(true);
        radMujer.setEnabled(true);
        radNadar.setEnabled(true);
        radNinguna.setEnabled(true);
        radOficina.setEnabled(true);
        radSeguridad.setEnabled(true);
        btnReiniciar.setEnabled(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        grpGenero = new javax.swing.ButtonGroup();
        grpFumador = new javax.swing.ButtonGroup();
        grpBebedor = new javax.swing.ButtonGroup();
        grpActividades = new javax.swing.ButtonGroup();
        grpTrabajo = new javax.swing.ButtonGroup();
        grpEnfermedades = new javax.swing.ButtonGroup();
        pnlEncabezado = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlOpciones = new javax.swing.JPanel();
        lblGenero = new javax.swing.JLabel();
        lblFumador = new javax.swing.JLabel();
        lblBebedor = new javax.swing.JLabel();
        lblActividad = new javax.swing.JLabel();
        lblTrabajo = new javax.swing.JLabel();
        lblEnfermedades = new javax.swing.JLabel();
        radHombre = new javax.swing.JRadioButton();
        radMujer = new javax.swing.JRadioButton();
        radFumadorSi = new javax.swing.JRadioButton();
        radFumadorNo = new javax.swing.JRadioButton();
        radBebedorNo = new javax.swing.JRadioButton();
        radBebedorSi = new javax.swing.JRadioButton();
        radCorrer = new javax.swing.JRadioButton();
        radNadar = new javax.swing.JRadioButton();
        radBoxeo = new javax.swing.JRadioButton();
        radNinguna = new javax.swing.JRadioButton();
        radOficina = new javax.swing.JRadioButton();
        radMaestro = new javax.swing.JRadioButton();
        radSeguridad = new javax.swing.JRadioButton();
        radCronicasSi = new javax.swing.JRadioButton();
        radCronicasNo = new javax.swing.JRadioButton();
        pnlAcciones = new javax.swing.JPanel();
        txtEdad = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        lblEdadActual = new javax.swing.JLabel();
        lblEsperanzaVida = new javax.swing.JLabel();
        lblPrediccionDeceso = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblEsperanza = new javax.swing.JLabel();
        lblDeceso = new javax.swing.JLabel();
        lblFechaDeceso = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlEncabezado.setBackground(new java.awt.Color(22, 75, 96));

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(213, 255, 208));
        lblTitulo.setText("¿Cuál es tu esperanza de vida?");

        javax.swing.GroupLayout pnlEncabezadoLayout = new javax.swing.GroupLayout(pnlEncabezado);
        pnlEncabezado.setLayout(pnlEncabezadoLayout);
        pnlEncabezadoLayout.setHorizontalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEncabezadoLayout.setVerticalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEncabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addContainerGap())
        );

        pnlOpciones.setBackground(new java.awt.Color(27, 107, 147));

        lblGenero.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblGenero.setForeground(new java.awt.Color(162, 255, 134));
        lblGenero.setText("Genero");

        lblFumador.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblFumador.setForeground(new java.awt.Color(162, 255, 134));
        lblFumador.setText("Fumador");

        lblBebedor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblBebedor.setForeground(new java.awt.Color(162, 255, 134));
        lblBebedor.setText("Bebedor");

        lblActividad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblActividad.setForeground(new java.awt.Color(162, 255, 134));
        lblActividad.setText("Tipo de actividad física");

        lblTrabajo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblTrabajo.setForeground(new java.awt.Color(162, 255, 134));
        lblTrabajo.setText("Tipo de trabajo");

        lblEnfermedades.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblEnfermedades.setForeground(new java.awt.Color(162, 255, 134));
        lblEnfermedades.setText("Enfermedades crónicas");

        grpGenero.add(radHombre);
        radHombre.setText("Hombre");
        radHombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radHombreMouseClicked(evt);
            }
        });
        radHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radHombreActionPerformed(evt);
            }
        });

        grpGenero.add(radMujer);
        radMujer.setText("Mujer");
        radMujer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radMujerMouseClicked(evt);
            }
        });

        grpFumador.add(radFumadorSi);
        radFumadorSi.setText("Si");
        radFumadorSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radFumadorSiMouseClicked(evt);
            }
        });

        grpFumador.add(radFumadorNo);
        radFumadorNo.setText("No");
        radFumadorNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radFumadorNoMouseClicked(evt);
            }
        });

        grpBebedor.add(radBebedorNo);
        radBebedorNo.setText("No");
        radBebedorNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radBebedorNoMouseClicked(evt);
            }
        });

        grpBebedor.add(radBebedorSi);
        radBebedorSi.setText("Si");
        radBebedorSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radBebedorSiMouseClicked(evt);
            }
        });

        grpActividades.add(radCorrer);
        radCorrer.setText("Correr");
        radCorrer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radCorrerMouseClicked(evt);
            }
        });

        grpActividades.add(radNadar);
        radNadar.setText("Nadar");
        radNadar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radNadarMouseClicked(evt);
            }
        });

        grpActividades.add(radBoxeo);
        radBoxeo.setText("Boxeo");
        radBoxeo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radBoxeoMouseClicked(evt);
            }
        });

        grpActividades.add(radNinguna);
        radNinguna.setText("Ninguna");
        radNinguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radNingunaMouseClicked(evt);
            }
        });

        grpTrabajo.add(radOficina);
        radOficina.setText("Oficina");
        radOficina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radOficinaMouseClicked(evt);
            }
        });

        grpTrabajo.add(radMaestro);
        radMaestro.setText("Maestro");
        radMaestro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radMaestroMouseClicked(evt);
            }
        });

        grpTrabajo.add(radSeguridad);
        radSeguridad.setText("Seguridad (Policia, guradía, etc)");
        radSeguridad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radSeguridadMouseClicked(evt);
            }
        });

        grpEnfermedades.add(radCronicasSi);
        radCronicasSi.setText("Si");
        radCronicasSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radCronicasSiMouseClicked(evt);
            }
        });

        grpEnfermedades.add(radCronicasNo);
        radCronicasNo.setText("No");
        radCronicasNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radCronicasNoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlOpcionesLayout = new javax.swing.GroupLayout(pnlOpciones);
        pnlOpciones.setLayout(pnlOpcionesLayout);
        pnlOpcionesLayout.setHorizontalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOpcionesLayout.createSequentialGroup()
                        .addComponent(radBebedorSi)
                        .addGap(64, 64, 64)
                        .addComponent(radBebedorNo))
                    .addComponent(lblBebedor)
                    .addGroup(pnlOpcionesLayout.createSequentialGroup()
                        .addComponent(radCronicasSi)
                        .addGap(64, 64, 64)
                        .addComponent(radCronicasNo))
                    .addComponent(lblTrabajo)
                    .addComponent(lblFumador)
                    .addGroup(pnlOpcionesLayout.createSequentialGroup()
                        .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                                .addComponent(radOficina)
                                .addGap(36, 36, 36)
                                .addComponent(radMaestro))
                            .addComponent(lblActividad)
                            .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlOpcionesLayout.createSequentialGroup()
                                    .addComponent(radCorrer)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(radNadar))
                                .addComponent(lblEnfermedades, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlOpcionesLayout.createSequentialGroup()
                                    .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlOpcionesLayout.createSequentialGroup()
                                            .addComponent(radHombre)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpcionesLayout.createSequentialGroup()
                                            .addComponent(radFumadorSi)
                                            .addGap(64, 64, 64)))
                                    .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(radMujer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(radFumadorNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(lblGenero))
                        .addGap(18, 18, 18)
                        .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                                .addComponent(radBoxeo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radNinguna))
                            .addComponent(radSeguridad))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlOpcionesLayout.setVerticalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblGenero)
                .addGap(9, 9, 9)
                .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radHombre)
                    .addComponent(radMujer))
                .addGap(16, 16, 16)
                .addComponent(lblFumador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radFumadorSi)
                    .addComponent(radFumadorNo))
                .addGap(15, 15, 15)
                .addComponent(lblBebedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radBebedorNo)
                    .addComponent(radBebedorSi))
                .addGap(12, 12, 12)
                .addComponent(lblActividad)
                .addGap(18, 18, 18)
                .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radCorrer)
                    .addComponent(radNadar)
                    .addComponent(radBoxeo)
                    .addComponent(radNinguna))
                .addGap(2, 2, 2)
                .addComponent(lblTrabajo)
                .addGap(13, 13, 13)
                .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radOficina)
                    .addComponent(radMaestro)
                    .addComponent(radSeguridad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEnfermedades)
                .addGap(18, 18, 18)
                .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radCronicasNo)
                    .addComponent(radCronicasSi))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pnlAcciones.setBackground(new java.awt.Color(79, 192, 208));

        btnCalcular.setBackground(new java.awt.Color(162, 255, 134));
        btnCalcular.setForeground(new java.awt.Color(12, 53, 106));
        btnCalcular.setText("Calcular");
        btnCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcularMouseClicked(evt);
            }
        });

        lblEdadActual.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblEdadActual.setForeground(new java.awt.Color(12, 53, 106));
        lblEdadActual.setText("Usted tiene");

        lblEsperanzaVida.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblEsperanzaVida.setForeground(new java.awt.Color(12, 53, 106));
        lblEsperanzaVida.setText("La esperanza de vida es");

        lblPrediccionDeceso.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblPrediccionDeceso.setForeground(new java.awt.Color(12, 53, 106));
        lblPrediccionDeceso.setText("Su deceso podría ser en");

        lblEdad.setForeground(new java.awt.Color(12, 53, 106));

        lblEsperanza.setForeground(new java.awt.Color(12, 53, 106));

        lblDeceso.setForeground(new java.awt.Color(12, 53, 106));

        lblFechaDeceso.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblFechaDeceso.setForeground(new java.awt.Color(12, 53, 106));
        lblFechaDeceso.setText("Su fecha de deceso sería");

        lblFecha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(12, 53, 106));

        btnReiniciar.setBackground(new java.awt.Color(162, 255, 134));
        btnReiniciar.setForeground(new java.awt.Color(12, 53, 106));
        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReiniciarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlAccionesLayout = new javax.swing.GroupLayout(pnlAcciones);
        pnlAcciones.setLayout(pnlAccionesLayout);
        pnlAccionesLayout.setHorizontalGroup(
            pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAccionesLayout.createSequentialGroup()
                        .addGroup(pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEdad)
                            .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(btnReiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccionesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccionesLayout.createSequentialGroup()
                                .addGroup(pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlAccionesLayout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(lblEdadActual))
                                    .addComponent(lblEsperanzaVida)
                                    .addComponent(lblPrediccionDeceso)
                                    .addGroup(pnlAccionesLayout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(lblEdad))
                                    .addGroup(pnlAccionesLayout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(lblEsperanza))
                                    .addGroup(pnlAccionesLayout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(lblDeceso))
                                    .addComponent(lblFechaDeceso))
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccionesLayout.createSequentialGroup()
                                .addComponent(lblFecha)
                                .addGap(82, 82, 82))))))
        );
        pnlAccionesLayout.setVerticalGroup(
            pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalcular)
                .addGap(18, 18, 18)
                .addComponent(btnReiniciar)
                .addGap(40, 40, 40)
                .addComponent(lblEdadActual)
                .addGap(18, 18, 18)
                .addComponent(lblEdad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEsperanzaVida)
                .addGap(18, 18, 18)
                .addComponent(lblEsperanza)
                .addGap(26, 26, 26)
                .addComponent(lblPrediccionDeceso)
                .addGap(18, 18, 18)
                .addComponent(lblDeceso)
                .addGap(35, 35, 35)
                .addComponent(lblFechaDeceso)
                .addGap(18, 18, 18)
                .addComponent(lblFecha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        disableButtons();
    }//GEN-LAST:event_formWindowOpened

    private void btnCalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMouseClicked
        // TODO add your handling code here
        if (txtEdad.getText().equals("")){
            JOptionPane.showMessageDialog(null, "La edad esta vacía");
        }else{
            try{
                NumberFormat.getInstance().parse(txtEdad.getText());
                edadActual = Integer.parseInt(txtEdad.getText());
                edadRestante = 75 - edadActual;
                if ( edadRestante <= 0){
                    JOptionPane.showMessageDialog(null, "No puede ser que su edad este en números negativos o sea 0");
                }
                else{
                    enableButtons();
                    lblEdad.setText(Integer.toString(edadActual));
                    lblEsperanza.setText("75");
                    txtEdad.setEnabled(false);
                    btnCalcular.setEnabled(false);
                    String strEdadRestante = Integer.toString(edadRestante);
                    lblDeceso.setText(strEdadRestante + " años");
                }
                
            }catch(ParseException e){
                JOptionPane.showMessageDialog(null, "Debes introducir un dato númerico");
            }
        }
    }//GEN-LAST:event_btnCalcularMouseClicked

    private void radHombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radHombreMouseClicked
        radMujer.setEnabled(false);
        edadRestante -= 3;
        String strEdadRestante = Integer.toString(edadRestante);
        lblDeceso.setText(strEdadRestante + " años");
        radHombre.setEnabled(false);
        lblFecha.setText("" + LocalDate.now().plusYears(edadRestante));
        // TODO add your handling code here:
    }//GEN-LAST:event_radHombreMouseClicked

    private void radMujerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radMujerMouseClicked
        // TODO add your handling code here:
        radHombre.setEnabled(false);
        edadRestante += 3;
        String strEdadRestante = Integer.toString(edadRestante);
        lblDeceso.setText(strEdadRestante + " años");
        radMujer.setEnabled(false);
        lblFecha.setText("" + LocalDate.now().plusYears(edadRestante));
    }//GEN-LAST:event_radMujerMouseClicked

    private void radFumadorSiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radFumadorSiMouseClicked
        // TODO add your handling code here:
        radFumadorNo.setEnabled(false);
        radFumadorSi.setEnabled(false);
        edadRestante -= 5;
        String strEdadRestante = Integer.toString(edadRestante);
        lblDeceso.setText(strEdadRestante + " años");
        lblFecha.setText("" + LocalDate.now().plusYears(edadRestante));
    }//GEN-LAST:event_radFumadorSiMouseClicked

    private void radFumadorNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radFumadorNoMouseClicked
        // TODO add your handling code here:
        radFumadorSi.setEnabled(false);
        radFumadorNo.setEnabled(false);
        edadRestante += 2;
        String strEdadRestante = Integer.toString(edadRestante);
        lblDeceso.setText(strEdadRestante + " años");
        lblFecha.setText("" + LocalDate.now().plusYears(edadRestante));
    }//GEN-LAST:event_radFumadorNoMouseClicked

    private void radBebedorSiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radBebedorSiMouseClicked
        // TODO add your handling code here:
        radBebedorNo.setEnabled(false);
        radBebedorSi.setEnabled(false);
        edadRestante -= 6;
        String strEdadRestante = Integer.toString(edadRestante);
        lblDeceso.setText(strEdadRestante + " años");
        lblFecha.setText("" + LocalDate.now().plusYears(edadRestante));
    }//GEN-LAST:event_radBebedorSiMouseClicked

    private void radBebedorNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radBebedorNoMouseClicked
        // TODO add your handling code here:
        radBebedorNo.setEnabled(false);
        radBebedorSi.setEnabled(false);
        edadRestante += 2;
        String strEdadRestante = Integer.toString(edadRestante);
        lblDeceso.setText(strEdadRestante + " años");
        lblFecha.setText("" + LocalDate.now().plusYears(edadRestante));
    }//GEN-LAST:event_radBebedorNoMouseClicked

    private void radCorrerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radCorrerMouseClicked
        // TODO add your handling code here:
        desactivarActividades();
        edadRestante += 3;
        String strEdadRestante = Integer.toString(edadRestante);
        lblDeceso.setText(strEdadRestante + " años");
        lblFecha.setText("" + LocalDate.now().plusYears(edadRestante));
    }//GEN-LAST:event_radCorrerMouseClicked

    private void radHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radHombreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_radHombreActionPerformed

    private void radNadarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radNadarMouseClicked
        // TODO add your handling code here:
        desactivarActividades();
        edadRestante += 5;
        String strEdadRestante = Integer.toString(edadRestante);
        lblDeceso.setText(strEdadRestante + " años");
        lblFecha.setText("" + LocalDate.now().plusYears(edadRestante));
    }//GEN-LAST:event_radNadarMouseClicked

    private void radBoxeoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radBoxeoMouseClicked
        // TODO add your handling code here:
        desactivarActividades();
        edadRestante -= 6;
        String strEdadRestante = Integer.toString(edadRestante);
        lblDeceso.setText(strEdadRestante + " años");
        lblFecha.setText("" + LocalDate.now().plusYears(edadRestante));
    }//GEN-LAST:event_radBoxeoMouseClicked

    private void radNingunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radNingunaMouseClicked
        // TODO add your handling code here:
        desactivarActividades();
        edadRestante -= 3;
        String strEdadRestante = Integer.toString(edadRestante);
        lblDeceso.setText(strEdadRestante + " años");
        lblFecha.setText("" + LocalDate.now().plusYears(edadRestante));
    }//GEN-LAST:event_radNingunaMouseClicked

    private void radOficinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radOficinaMouseClicked
        // TODO add your handling code here:
        desactivarTrabajos();
        edadRestante -= 3;
        String strEdadRestante = Integer.toString(edadRestante);
        lblDeceso.setText(strEdadRestante + " años");
        lblFecha.setText("" + LocalDate.now().plusYears(edadRestante));
    }//GEN-LAST:event_radOficinaMouseClicked

    private void radMaestroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radMaestroMouseClicked
        // TODO add your handling code here:
        desactivarTrabajos();
        edadRestante += 2;
        String strEdadRestante = Integer.toString(edadRestante);
        lblDeceso.setText(strEdadRestante + " años");
        lblFecha.setText("" + LocalDate.now().plusYears(edadRestante));
    }//GEN-LAST:event_radMaestroMouseClicked

    private void radSeguridadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radSeguridadMouseClicked
        // TODO add your handling code here:
        desactivarTrabajos();
        edadRestante -= 4;
        String strEdadRestante = Integer.toString(edadRestante);
        lblDeceso.setText(strEdadRestante + " años");
        lblFecha.setText("" + LocalDate.now().plusYears(edadRestante));
    }//GEN-LAST:event_radSeguridadMouseClicked

    private void radCronicasSiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radCronicasSiMouseClicked
        // TODO add your handling code here:
        radCronicasNo.setEnabled(false);
        radCronicasSi.setEnabled(false);
        edadRestante -= 4;
        String strEdadRestante = Integer.toString(edadRestante);
        lblDeceso.setText(strEdadRestante + " años");
        lblFecha.setText("" + LocalDate.now().plusYears(edadRestante));
    }//GEN-LAST:event_radCronicasSiMouseClicked

    private void radCronicasNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radCronicasNoMouseClicked
        // TODO add your handling code here:
         radCronicasNo.setEnabled(false);
        radCronicasSi.setEnabled(false);
        edadRestante += 2;
        String strEdadRestante = Integer.toString(edadRestante);
        lblDeceso.setText(strEdadRestante + " años");
        lblFecha.setText("" + LocalDate.now().plusYears(edadRestante));
    }//GEN-LAST:event_radCronicasNoMouseClicked

    private void btnReiniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReiniciarMouseClicked
        // TODO add your handling code here:
        disableButtons();
        uncheckRadioButtons();
        txtEdad.setEnabled(true);
        btnCalcular.setEnabled(true);
        edadActual = 0;
        edadRestante = 0;
        lblDeceso.setText("");
        lblFecha.setText("");
        lblEdad.setText("");
        lblEsperanza.setText("");
        txtEdad.setText("");
        btnReiniciar.setEnabled(false);
    }//GEN-LAST:event_btnReiniciarMouseClicked

    public void desactivarActividades(){
        radNadar.setEnabled(false);
        radBoxeo.setEnabled(false);
        radNinguna.setEnabled(false);
        radCorrer.setEnabled(false);
    }
           
    public void desactivarTrabajos(){
        radOficina.setEnabled(false);
        radMaestro.setEnabled(false);
        radSeguridad.setEnabled(false);
    }
    
    public void uncheckRadioButtons(){
        grpActividades.clearSelection();
        grpBebedor.clearSelection();
        grpEnfermedades.clearSelection();
        grpFumador.clearSelection();
        grpGenero.clearSelection();
        grpTrabajo.clearSelection();
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.ButtonGroup grpActividades;
    private javax.swing.ButtonGroup grpBebedor;
    private javax.swing.ButtonGroup grpEnfermedades;
    private javax.swing.ButtonGroup grpFumador;
    private javax.swing.ButtonGroup grpGenero;
    private javax.swing.ButtonGroup grpTrabajo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblActividad;
    private javax.swing.JLabel lblBebedor;
    private javax.swing.JLabel lblDeceso;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEdadActual;
    private javax.swing.JLabel lblEnfermedades;
    private javax.swing.JLabel lblEsperanza;
    private javax.swing.JLabel lblEsperanzaVida;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaDeceso;
    private javax.swing.JLabel lblFumador;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblPrediccionDeceso;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTrabajo;
    private javax.swing.JPanel pnlAcciones;
    private javax.swing.JPanel pnlEncabezado;
    private javax.swing.JPanel pnlOpciones;
    private javax.swing.JRadioButton radBebedorNo;
    private javax.swing.JRadioButton radBebedorSi;
    private javax.swing.JRadioButton radBoxeo;
    private javax.swing.JRadioButton radCorrer;
    private javax.swing.JRadioButton radCronicasNo;
    private javax.swing.JRadioButton radCronicasSi;
    private javax.swing.JRadioButton radFumadorNo;
    private javax.swing.JRadioButton radFumadorSi;
    private javax.swing.JRadioButton radHombre;
    private javax.swing.JRadioButton radMaestro;
    private javax.swing.JRadioButton radMujer;
    private javax.swing.JRadioButton radNadar;
    private javax.swing.JRadioButton radNinguna;
    private javax.swing.JRadioButton radOficina;
    private javax.swing.JRadioButton radSeguridad;
    private javax.swing.JTextField txtEdad;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mousePressed(MouseEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseReleased(MouseEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseEntered(MouseEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void mouseExited(MouseEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
