
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC
 */
public class Figuras extends javax.swing.JFrame {

   
    public Figuras() {
        initComponents();
        

        
        
        CnvFig.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent me) {
            Point coord = me.getPoint();
    Graphics grp = CnvFig.getGraphics();
    grp.drawOval(coord.x - 2, coord.y - 2, 4, 4);    

            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mousePressed(MouseEvent me) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseReleased(MouseEvent me) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseEntered(MouseEvent me) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseExited(MouseEvent me) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnCir = new javax.swing.JButton();
        BtnRect = new javax.swing.JButton();
        BtnLine = new javax.swing.JButton();
        BtnTri = new javax.swing.JButton();
        TxtCrx = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CnvFig = new java.awt.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnCir.setText("Circulo");
        BtnCir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCirActionPerformed(evt);
            }
        });

        BtnRect.setText("Rectangulo");
        BtnRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRectActionPerformed(evt);
            }
        });

        BtnLine.setText("Linea");
        BtnLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLineActionPerformed(evt);
            }
        });

        BtnTri.setText("Triangulo");
        BtnTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTriActionPerformed(evt);
            }
        });

        TxtCrx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCrxActionPerformed(evt);
            }
        });

        jLabel1.setText("Introduzca el valor del tamaño de la figura");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CnvFig, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnCir)
                                .addGap(18, 18, 18)
                                .addComponent(BtnRect))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtCrx))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnLine)
                        .addGap(18, 18, 18)
                        .addComponent(BtnTri)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(TxtCrx, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CnvFig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCir)
                    .addComponent(BtnRect)
                    .addComponent(BtnLine)
                    .addComponent(BtnTri))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCrxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCrxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCrxActionPerformed

    private void BtnCirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCirActionPerformed

    int Xc1 = Integer.parseInt(TxtCrx.getText());
        BtnCir.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent mec) {
            Point coord = mec.getPoint();
            Graphics grp = CnvFig.getGraphics();
            grp.drawOval(coord.x - 1, coord.y - 1, Xc1,Xc1);
            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mousePressed(MouseEvent mec) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseReleased(MouseEvent mec) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseEntered(MouseEvent mec) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseExited(MouseEvent mec) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });

    }//GEN-LAST:event_BtnCirActionPerformed

    private void BtnRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRectActionPerformed
      
    int Xr1 = Integer.parseInt(TxtCrx.getText());    
        BtnRect.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent mel) {   
            Point coord = mel.getPoint();
            Graphics grp1 = CnvFig.getGraphics();
            Graphics grp2 = CnvFig.getGraphics();
            Graphics grp3 = CnvFig.getGraphics();
            Graphics grp4 = CnvFig.getGraphics();
            grp1.drawLine(coord.x - 10000, coord.y - 0, Xr1, 0);
            grp2.drawLine(coord.x - 20000, coord.y - 0, Xr1, Xr1/2);
            grp3.drawLine(coord.x - 0, coord.y - 10000, 0, Xr1/2);
            grp4.drawLine(coord.x - 0, coord.y - 10000, Xr1, Xr1/2);
           
            }

            @Override
            public void mousePressed(MouseEvent mel) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseReleased(MouseEvent mel) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseEntered(MouseEvent mel) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseExited(MouseEvent mel) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        
    }//GEN-LAST:event_BtnRectActionPerformed

    private void BtnLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLineActionPerformed
        
    int Xl = Integer.parseInt(TxtCrx.getText());
        BtnLine.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent mel) {
            Point coord = mel.getPoint();
            Graphics grp1 = CnvFig.getGraphics();
            grp1.drawLine(coord.x - 20000, coord.y - 0, Xl, 100);
            
            }

            @Override
            public void mousePressed(MouseEvent me) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseReleased(MouseEvent me) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseEntered(MouseEvent me) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseExited(MouseEvent me) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        
    }//GEN-LAST:event_BtnLineActionPerformed

    private void BtnTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTriActionPerformed

    int XT = Integer.parseInt(TxtCrx.getText());    
        BtnTri.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent met) {
            Point coord = met.getPoint();
            Graphics grp1 = CnvFig.getGraphics();
            Graphics grp2 = CnvFig.getGraphics();
            Graphics grp3 = CnvFig.getGraphics();

            grp1.drawLine(coord.x - 20000, coord.y - 0, XT, XT/2);
            grp2.drawLine(coord.x - 10000, coord.y - 10000, XT, XT/2);
            grp3.drawLine(coord.x + 10000, coord.y - 10000, 0, XT/2);
            }

            @Override
            public void mousePressed(MouseEvent met) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseReleased(MouseEvent met) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseEntered(MouseEvent met) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseExited(MouseEvent met) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        
    }//GEN-LAST:event_BtnTriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Figuras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Figuras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCir;
    private javax.swing.JButton BtnLine;
    private javax.swing.JButton BtnRect;
    private javax.swing.JButton BtnTri;
    private java.awt.Canvas CnvFig;
    private javax.swing.JTextField TxtCrx;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
